version: '2.0'

volumes:
  dbdata:
  uploads:

services:
  postgres:
    container_name: db
    image: postgres:15.3
    environment:
      - POSTGRES_DB=szakdolgozat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Husleves2000*
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 6543
        protocol: tcp
        mode: host
  backend:
    container_name: backend
    image: szakdolgozat-backend
    build:
      context: ./spring-boot
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/szakdolgozat
    volumes:
      - uploads:/app/uploads
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    image: szakdolgozat-frontend
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
