volumes:
  dbdata:

services:
  postgres:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=szakdolgozat
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Husleves2000*
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    container_name: backend
    build:
      context: ./spring-boot
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/szakdolgozat
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    build:
      context: ./angular
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
